language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t kenshiva/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kenshiva/react-test npm test -- --coverage

after_success:
  - docker build -t kenshiva/multi-client ./client
  - docker build -t kenshiva/multi-nginx ./nginx
  - docker build -t kenshiva/multi-server ./server
  - docker build -t kenshiva/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -- password-stdin
  # Take those images and push them to docker hub
  - docker push kenshiva/multi-client
  - docker push kenshiva/multi-nginx
  - docker push kenshiva/multi-server
  - docker push kenshiva/multi-worker